### ISSUE TITLE
Mixing issue

### ISSUE THREAD

**Issue by zyr3x** [Ometria/magento2-extension#23]
Hi Guys. We have error in  configurable-mixin.js mixin. 
If i want something extend our module and add Ometria_Core in module.xml <sequence> <module name="Ometria_Core"/>  in </sequence> my module which also has  configurable-mixin.js. this will brake my module.

https://github.com/Ometria/magento2-extension/blob/master/app/code/Ometria/Core/view/frontend/web/js/configurable-mixin.js

**Actual:**
   return $.mage.Configurable;

**Expected:**
   return $.mage.configurable;

**Comment by chris-pook** [comment]
Thanks @zyr3x , this is fixed in release 2.1.1.
