### ISSUE TITLE
Baskets are expiring very quickly

### ISSUE THREAD

**Issue by aasim110** [Ometria/magento2-extension#5]
Hello There, 
We are getting an issue in Abandonment cart, you can check below for more information.
**The baskets are expiring very quickly and when customers clicking through the abandoned basket emails simply get an error saying their basket has expired.**

We are using magento 2.2.1 version and Ometria_AbandonedCarts 1.3.4 version.
eagerly waiting for your answer.

Thanks,
Aasim Goriya

**Comment by svisser** [comment]
@aasim110 hi there, thanks for letting us know.

Would you be okay with emailing this to support@ometria.com including client details so we can investigate?

**Comment by aasim110** [comment]
@svisser  sent email on support@ometria.com, please check and help to find solution.

**Comment by svisser** [comment]
Thanks for that, our support team will be able to help, please provide them with any information they may need to investigate this.

I'll close this Github issue as a result.
